/** Sample catalog for the NAYAN SECURITY preview. Not live inventory, verification, or reviews. */
export const SAMPLE_NOTE =
  "Sample data for this preview. Not a live listing, verification, review, order, or payment.";

export const cities = [
  { id: "bikaner", name: "Bikaner", state: "Rajasthan", areas: ["Station Road", "Rani Bazar", "Kote Gate", "JNV Colony", "Gangashahar"] },
  { id: "jaipur", name: "Jaipur", state: "Rajasthan", areas: ["MI Road", "Vaishali Nagar", "Malviya Nagar", "C-Scheme"] },
  { id: "jodhpur", name: "Jodhpur", state: "Rajasthan", areas: ["Sardarpura", "Paota", "Ratanada"] },
  { id: "udaipur", name: "Udaipur", state: "Rajasthan", areas: ["Hiran Magri", "Fatehpura", "Bapu Bazar"] },
  { id: "delhi", name: "Delhi", state: "Delhi", areas: ["Karol Bagh", "Lajpat Nagar", "Dwarka"] },
];

export const productCategories = [
  { id: "cctv-cameras", name: "CCTV Cameras", blurb: "Indoor and outdoor cameras for homes and shops." },
  { id: "ip-cameras", name: "IP Cameras", blurb: "Network cameras for NVR and PoE setups." },
  { id: "wifi-cameras", name: "Wi-Fi Cameras", blurb: "Cameras that join an existing wireless network." },
  { id: "dome-cameras", name: "Dome Cameras", blurb: "Compact ceiling cameras for rooms and counters." },
  { id: "bullet-cameras", name: "Bullet Cameras", blurb: "Directional outdoor cameras with a sun shield." },
  { id: "ptz-cameras", name: "PTZ Cameras", blurb: "Pan, tilt and zoom for wider coverage." },
  { id: "4g-cameras", name: "4G Cameras", blurb: "Cameras for sites without a fixed broadband line." },
  { id: "dvr", name: "DVR", blurb: "Recorders for coaxial camera systems." },
  { id: "nvr", name: "NVR", blurb: "Recorders for IP and PoE cameras." },
  { id: "hdd", name: "HDD", blurb: "Surveillance-grade storage for recorders." },
  { id: "poe-switch", name: "PoE Switch", blurb: "Power and data for IP cameras on one cable." },
  { id: "cat6", name: "CAT6 Cable", blurb: "Network cable for cameras and recorders." },
  { id: "power-supply", name: "Power Supply", blurb: "Adapters and SMPS for camera power." },
  { id: "bnc-rj45", name: "BNC/RJ45", blurb: "Connectors for coax and network runs." },
  { id: "memory-card", name: "Memory Card", blurb: "Local storage for selected cameras." },
  { id: "ups", name: "UPS", blurb: "Short backup for recorders during outages." },
  { id: "cctv-kits", name: "CCTV Kits", blurb: "Cameras, recorder and basics in one set." },
  { id: "accessories", name: "Accessories", blurb: "Mounts, connectors and small parts." },
];

export const shops = [
  {
    id: "karni-cctv",
    name: "Karni CCTV House",
    city: "bikaner",
    area: "Station Road",
    hours: "Mon–Sat, 10:00–20:00",
    about: "Sample shop profile for a local CCTV counter. Product range, hours and services below are layout content, not a live storefront.",
    services: ["Product sales", "Installation", "Repair", "Delivery in listed areas"],
    productsNote: "Cameras, recorders, cable and kits",
    image: "/images/install-scene.jpg",
    imageAlt: "A technician fitting a white camera under a shop awning on a market street",
    rating: 4.7,
    reviewCount: 3,
    deliveryCities: ["bikaner"],
    install: true,
    repair: true,
  },
  {
    id: "rampuria-mart",
    name: "Rampuria Security Mart",
    city: "bikaner",
    area: "Rani Bazar",
    hours: "Mon–Sat, 10:30–19:30",
    about: "Sample seller focused on home kits and accessories. Verification is not connected.",
    services: ["Product sales", "Shop pickup", "Basic installation"],
    productsNote: "Home kits, Wi-Fi cameras, accessories",
    image: "/images/hero-camera.jpg",
    imageAlt: "A white security camera on a limestone home exterior",
    rating: 4.5,
    reviewCount: 2,
    deliveryCities: ["bikaner"],
    install: true,
    repair: false,
  },
  {
    id: "amber-view",
    name: "Amber View Systems",
    city: "jaipur",
    area: "MI Road",
    hours: "Mon–Sat, 10:00–19:00",
    about: "Sample Jaipur seller profile for IP cameras, NVRs and PoE gear.",
    services: ["Product sales", "Installation", "Business quotes"],
    productsNote: "IP cameras, NVR, PoE, cable",
    image: "/images/ptz-cam.jpg",
    imageAlt: "A white PTZ camera mounted on a pale wall",
    rating: 4.6,
    reviewCount: 2,
    deliveryCities: ["jaipur"],
    install: true,
    repair: true,
  },
  {
    id: "desert-lens",
    name: "Desert Lens Security",
    city: "jodhpur",
    area: "Sardarpura",
    hours: "Mon–Sat, 11:00–20:00",
    about: "Sample Jodhpur shop profile. Delivery areas in this preview are illustrative.",
    services: ["Product sales", "Repair desk", "Pickup"],
    productsNote: "Bullet cameras, DVR, storage, power",
    image: "/images/bullet-cam.jpg",
    imageAlt: "A white outdoor bullet camera on a studio wall",
    rating: 4.4,
    reviewCount: 2,
    deliveryCities: ["jodhpur"],
    install: false,
    repair: true,
  },
];

export const professionals = [
  {
    id: "r-sharma",
    name: "R. Sharma",
    business: "Sharma Field Install",
    city: "bikaner",
    area: "Kote Gate",
    services: ["cctv-installation", "cctv-wiring", "ip-camera-setup", "remote-viewing"],
    hours: "Mon–Sat, 10:00–19:00",
    experienceLabel: "Listed as 6 years · sample profile",
    starting: 1499,
    bio: "Sample installer profile for home and small-shop camera work in Bikaner. This person is not a live, verified professional on NAYAN SECURITY.",
    portfolio: [
      { src: "/images/install-scene.jpg", alt: "Sample installation scene on a market street", caption: "Sample image · not this profile’s work" },
      { src: "/images/hero-camera.jpg", alt: "Camera on a limestone exterior", caption: "Sample image · not this profile’s work" },
    ],
  },
  {
    id: "n-khan",
    name: "N. Khan",
    business: "Khan CCTV Service",
    city: "bikaner",
    area: "Gangashahar",
    services: ["cctv-repair", "dvr-nvr-service", "cctv-maintenance", "cctv-inspection"],
    hours: "Mon–Sat, 09:30–18:30",
    experienceLabel: "Listed as 8 years · sample profile",
    starting: null,
    bio: "Sample repair profile. Quote-based visits are shown as a workflow, not as a booked technician.",
    portfolio: [
      { src: "/images/nvr.jpg", alt: "A black network recorder on a studio surface", caption: "Sample image · not this profile’s work" },
    ],
  },
  {
    id: "meera-co",
    name: "Meera & Co.",
    business: "Meera Security Desk",
    city: "jaipur",
    area: "Vaishali Nagar",
    services: ["cctv-installation", "wifi-camera-setup", "remote-viewing", "amc"],
    hours: "Mon–Sat, 10:00–19:00",
    experienceLabel: "Listed as 5 years · sample profile",
    starting: 1799,
    bio: "Sample Jaipur service desk for Wi-Fi cameras, remote viewing and AMC conversations.",
    portfolio: [
      { src: "/images/wifi-cam.jpg", alt: "A white indoor Wi-Fi camera on a stand", caption: "Sample image · not this profile’s work" },
    ],
  },
  {
    id: "arjun-field",
    name: "Arjun Field Services",
    business: "Arjun Field Services",
    city: "jodhpur",
    area: "Paota",
    services: ["cctv-installation", "4g-camera-setup", "cctv-wiring", "cctv-repair"],
    hours: "Mon–Sat, 10:00–18:00",
    experienceLabel: "Listed as 7 years · sample profile",
    starting: 1999,
    bio: "Sample profile for outdoor and 4G camera work. Availability is not live.",
    portfolio: [
      { src: "/images/4g-cam.jpg", alt: "A white 4G camera with a small solar panel", caption: "Sample image · not this profile’s work" },
    ],
  },
  {
    id: "s-rathore",
    name: "S. Rathore",
    business: "Rathore Camera Works",
    city: "udaipur",
    area: "Hiran Magri",
    services: ["cctv-installation", "ptz", "ip-camera-setup", "cctv-inspection"],
    hours: "Tue–Sun, 11:00–19:00",
    experienceLabel: "Listed as 4 years · sample profile",
    starting: 1699,
    bio: "Sample Udaipur profile. PTZ and inspection requests would be quoted after a site look.",
    portfolio: [
      { src: "/images/ptz-cam.jpg", alt: "A white PTZ camera", caption: "Sample image · not this profile’s work" },
    ],
  },
  {
    id: "p-verma",
    name: "P. Verma",
    business: "Verma Secure",
    city: "delhi",
    area: "Karol Bagh",
    services: ["cctv-repair", "dvr-nvr-service", "remote-viewing", "amc"],
    hours: "Mon–Sat, 10:00–19:00",
    experienceLabel: "Listed as 9 years · sample profile",
    starting: null,
    bio: "Sample Delhi profile for recorder faults and remote-viewing setup. Not bookable in this preview.",
    portfolio: [
      { src: "/images/nvr.jpg", alt: "A black recorder", caption: "Sample image · not this profile’s work" },
    ],
  },
];

const spec = (rows) => rows;

export const products = [
  {
    id: "dome-2mp",
    name: "Indoor dome camera, 2MP",
    brand: "Aurora Demo",
    model: "AD-D2",
    sku: "SAMPLE-AD-D2",
    categories: ["cctv-cameras", "ip-cameras", "dome-cameras"],
    seller: "karni-cctv",
    image: "/images/dome-cam.jpg",
    alt: "White indoor dome security camera on a warm studio background",
    mrp: 2499,
    price: 2049,
    stock: 8,
    warranty: "12 months · sample label",
    rating: 4.6,
    resolution: "2MP",
    lens: "2.8 mm fixed",
    night: "IR up to 20 m · sample spec",
    storage: "Recorder or NVR",
    connectivity: "IP / PoE",
    description: "Sample indoor dome for rooms, counters and small offices. Specifications are catalog placeholders, not a manufacturer datasheet.",
    specs: spec([
      ["Resolution", "2MP (sample)"],
      ["Lens", "2.8 mm"],
      ["Night vision", "Infrared, short range"],
      ["Connectivity", "Network / PoE"],
      ["Use", "Indoor"],
      ["Weather", "Not listed as outdoor"],
    ]),
  },
  {
    id: "bullet-4mp",
    name: "Outdoor bullet camera, 4MP",
    brand: "Aurora Demo",
    model: "AD-B4",
    sku: "SAMPLE-AD-B4",
    categories: ["cctv-cameras", "ip-cameras", "bullet-cameras"],
    seller: "karni-cctv",
    image: "/images/bullet-cam.jpg",
    alt: "White outdoor bullet security camera with a sun shield",
    mrp: 4299,
    price: 3599,
    stock: 5,
    warranty: "24 months · sample label",
    rating: 4.8,
    resolution: "4MP",
    lens: "2.8 mm",
    night: "IR up to 30 m · sample spec",
    storage: "NVR",
    connectivity: "IP / PoE",
    description: "Sample outdoor bullet camera for gates, shopfronts and boundary walls. Confirm outdoor rating on the final quote.",
    specs: spec([
      ["Resolution", "4MP (sample)"],
      ["Form", "Bullet with sun shield"],
      ["Night vision", "Infrared"],
      ["Connectivity", "Network / PoE"],
      ["Use", "Outdoor · sample listing"],
    ]),
  },
  {
    id: "wifi-indoor",
    name: "Indoor Wi-Fi camera",
    brand: "Lumen Demo",
    model: "LD-W1",
    sku: "SAMPLE-LD-W1",
    categories: ["cctv-cameras", "wifi-cameras"],
    seller: "rampuria-mart",
    image: "/images/wifi-cam.jpg",
    alt: "Small white indoor Wi-Fi camera on a stand",
    mrp: 2199,
    price: 1799,
    stock: 12,
    warranty: "12 months · sample label",
    rating: 4.4,
    resolution: "2MP",
    lens: "Fixed",
    night: "IR · sample spec",
    storage: "Memory card slot · sample",
    connectivity: "Wi-Fi",
    description: "Sample Wi-Fi camera for a room that already has a router. Remote viewing still depends on the network and app setup.",
    specs: spec([
      ["Resolution", "2MP (sample)"],
      ["Connectivity", "Wi-Fi"],
      ["Power", "Adapter"],
      ["Storage", "Card slot listed as sample"],
      ["Use", "Indoor"],
    ]),
  },
  {
    id: "ptz-4mp",
    name: "PTZ camera, 4MP",
    brand: "Sentra Demo",
    model: "SD-P4",
    sku: "SAMPLE-SD-P4",
    categories: ["cctv-cameras", "ip-cameras", "ptz-cameras"],
    seller: "amber-view",
    image: "/images/ptz-cam.jpg",
    alt: "White PTZ speed-dome camera on a wall mount",
    mrp: 12999,
    price: 10999,
    stock: 3,
    warranty: "12 months · sample label",
    rating: 4.5,
    resolution: "4MP",
    lens: "Motorised zoom · sample",
    night: "IR · sample spec",
    storage: "NVR",
    connectivity: "IP / PoE",
    description: "Sample pan-tilt-zoom camera for a yard, warehouse aisle or shop floor. Mounting and network load should be quoted.",
    specs: spec([
      ["Resolution", "4MP (sample)"],
      ["Movement", "Pan, tilt, zoom"],
      ["Connectivity", "Network / PoE"],
      ["Mount", "Wall arm shown"],
    ]),
  },
  {
    id: "4g-solar",
    name: "4G camera with solar panel",
    brand: "Field Demo",
    model: "FD-4G",
    sku: "SAMPLE-FD-4G",
    categories: ["cctv-cameras", "4g-cameras"],
    seller: "desert-lens",
    image: "/images/4g-cam.jpg",
    alt: "White 4G security camera with a small solar panel and antenna",
    mrp: 8999,
    price: 7699,
    stock: 4,
    warranty: "12 months · sample label",
    rating: 4.3,
    resolution: "2MP",
    lens: "Fixed",
    night: "White LEDs · sample spec",
    storage: "Card · sample",
    connectivity: "4G",
    description: "Sample 4G camera for a site without a fixed broadband line. SIM, data plan and sun exposure are not included.",
    specs: spec([
      ["Connectivity", "4G · SIM not included"],
      ["Power", "Solar panel shown · sample"],
      ["Use", "Outdoor · confirm on quote"],
    ]),
  },
  {
    id: "nvr-8ch",
    name: "8-channel network recorder",
    brand: "Sentra Demo",
    model: "SD-N8",
    sku: "SAMPLE-SD-N8",
    categories: ["nvr"],
    seller: "amber-view",
    image: "/images/nvr.jpg",
    alt: "Slim black network video recorder on a warm studio surface",
    mrp: 7499,
    price: 6299,
    stock: 6,
    warranty: "24 months · sample label",
    rating: 4.7,
    resolution: "Up to listed camera resolution",
    lens: "—",
    night: "—",
    storage: "1 bay · HDD separate",
    connectivity: "Network",
    description: "Sample 8-channel NVR. Hard disk is sold separately in this catalog. Channel count is a sample specification.",
    specs: spec([
      ["Channels", "8 (sample)"],
      ["Storage bay", "1 · disk not included"],
      ["Outputs", "HDMI listed as sample"],
      ["Network", "Ethernet"],
    ]),
  },
  {
    id: "dvr-4ch",
    name: "4-channel DVR",
    brand: "Sentra Demo",
    model: "SD-D4",
    sku: "SAMPLE-SD-D4",
    categories: ["dvr"],
    seller: "desert-lens",
    image: "/images/svg/dvr.svg",
    alt: "Illustrated black digital video recorder",
    mrp: 3999,
    price: 3299,
    stock: 7,
    warranty: "12 months · sample label",
    rating: 4.2,
    resolution: "Depends on cameras",
    lens: "—",
    night: "—",
    storage: "HDD separate",
    connectivity: "BNC inputs · sample",
    description: "Sample DVR for a small coaxial system. Illustration, not a product photograph. Pair with compatible cameras on a quote.",
    specs: spec([
      ["Channels", "4 (sample)"],
      ["Inputs", "BNC listed as sample"],
      ["Storage", "Disk sold separately"],
    ]),
  },
  {
    id: "hdd-2tb",
    name: "Surveillance hard disk, 2TB",
    brand: "Line Demo",
    model: "LD-H2",
    sku: "SAMPLE-LD-H2",
    categories: ["hdd"],
    seller: "karni-cctv",
    image: "/images/hdd.jpg",
    alt: "Black 3.5 inch hard disk standing on a studio surface",
    mrp: 5499,
    price: 4799,
    stock: 9,
    warranty: "24 months · sample label",
    rating: 4.6,
    resolution: "—",
    lens: "—",
    night: "—",
    storage: "2TB",
    connectivity: "Recorder bay",
    description: "Sample 2TB disk intended for a recorder bay. Recording days depend on camera count and quality settings.",
    specs: spec([
      ["Capacity", "2TB (sample)"],
      ["Form", "3.5 inch"],
      ["Use", "Surveillance listing · sample"],
    ]),
  },
  {
    id: "poe-8",
    name: "8-port PoE switch",
    brand: "Line Demo",
    model: "LD-P8",
    sku: "SAMPLE-LD-P8",
    categories: ["poe-switch"],
    seller: "amber-view",
    image: "/images/poe-switch.jpg",
    alt: "Black 8-port PoE network switch",
    mrp: 3499,
    price: 2899,
    stock: 10,
    warranty: "12 months · sample label",
    rating: 4.5,
    resolution: "—",
    lens: "—",
    night: "—",
    storage: "—",
    connectivity: "8 PoE ports · sample",
    description: "Sample PoE switch to power IP cameras over the network cable. Check total power budget before a large install.",
    specs: spec([
      ["Ports", "8 (sample)"],
      ["Role", "Power and data"],
      ["Uplink", "Listed as sample"],
    ]),
  },
  {
    id: "cat6-305",
    name: "CAT6 cable box, 305 m",
    brand: "Line Demo",
    model: "LD-C6",
    sku: "SAMPLE-LD-C6",
    categories: ["cat6"],
    seller: "karni-cctv",
    image: "/images/svg/cat6.svg",
    alt: "Illustration of a coil of network cable",
    mrp: 6999,
    price: 5899,
    stock: 4,
    warranty: "Cable warranty · sample label",
    rating: 4.4,
    resolution: "—",
    lens: "—",
    night: "—",
    storage: "—",
    connectivity: "CAT6",
    description: "Sample 305 m box for camera runs. Actual length needed is measured on site.",
    specs: spec([
      ["Length", "305 m (sample)"],
      ["Type", "CAT6"],
      ["Use", "Camera and recorder cabling"],
    ]),
  },
  {
    id: "psu-12v",
    name: "12V camera power adapter",
    brand: "Line Demo",
    model: "LD-A12",
    sku: "SAMPLE-LD-A12",
    categories: ["power-supply"],
    seller: "rampuria-mart",
    image: "/images/svg/power.svg",
    alt: "Illustration of a camera power adapter",
    mrp: 499,
    price: 349,
    stock: 20,
    warranty: "6 months · sample label",
    rating: 4.1,
    resolution: "—",
    lens: "—",
    night: "—",
    storage: "—",
    connectivity: "12V DC · sample",
    description: "Sample adapter for cameras that are not powered by PoE. Match voltage and connector before use.",
    specs: spec([
      ["Output", "12V DC (sample)"],
      ["Use", "Single camera adapter"],
    ]),
  },
  {
    id: "smps-10a",
    name: "SMPS power supply, 10A",
    brand: "Line Demo",
    model: "LD-S10",
    sku: "SAMPLE-LD-S10",
    categories: ["power-supply"],
    seller: "desert-lens",
    image: "/images/svg/smps.svg",
    alt: "Illustration of an SMPS power supply box",
    mrp: 1499,
    price: 1199,
    stock: 6,
    warranty: "12 months · sample label",
    rating: 4.3,
    resolution: "—",
    lens: "—",
    night: "—",
    storage: "—",
    connectivity: "Multi-camera power · sample",
    description: "Sample SMPS for a small camera group. Load must be checked against the camera count.",
    specs: spec([
      ["Rating", "10A (sample)"],
      ["Use", "Shared camera power"],
    ]),
  },
  {
    id: "connector-pack",
    name: "BNC and RJ45 connector pack",
    brand: "Line Demo",
    model: "LD-CN",
    sku: "SAMPLE-LD-CN",
    categories: ["bnc-rj45", "accessories"],
    seller: "karni-cctv",
    image: "/images/svg/connectors.svg",
    alt: "Illustration of BNC and RJ45 connectors",
    mrp: 699,
    price: 499,
    stock: 15,
    warranty: "Parts · sample label",
    rating: 4.0,
    resolution: "—",
    lens: "—",
    night: "—",
    storage: "—",
    connectivity: "BNC + RJ45",
    description: "Sample mixed connector pack for terminations. Quantity in a real job comes from the cable plan.",
    specs: spec([
      ["Contents", "BNC and RJ45 · sample mix"],
      ["Use", "Terminations"],
    ]),
  },
  {
    id: "sd-128",
    name: "Memory card, 128GB",
    brand: "Lumen Demo",
    model: "LD-M128",
    sku: "SAMPLE-LD-M128",
    categories: ["memory-card"],
    seller: "rampuria-mart",
    image: "/images/svg/memory.svg",
    alt: "Illustration of a memory card",
    mrp: 1299,
    price: 999,
    stock: 11,
    warranty: "12 months · sample label",
    rating: 4.2,
    resolution: "—",
    lens: "—",
    night: "—",
    storage: "128GB",
    connectivity: "Camera slot",
    description: "Sample card for cameras that record locally. Not every camera in this catalog uses a card.",
    specs: spec([
      ["Capacity", "128GB (sample)"],
      ["Use", "Selected cameras"],
    ]),
  },
  {
    id: "ups-600",
    name: "UPS for recorder, 600VA",
    brand: "Line Demo",
    model: "LD-U6",
    sku: "SAMPLE-LD-U6",
    categories: ["ups"],
    seller: "amber-view",
    image: "/images/svg/ups.svg",
    alt: "Illustration of a small UPS",
    mrp: 3499,
    price: 2999,
    stock: 0,
    warranty: "12 months · sample label",
    rating: 4.1,
    resolution: "—",
    lens: "—",
    night: "—",
    storage: "—",
    connectivity: "Recorder backup",
    description: "Sample UPS listing, currently out of stock in this preview catalog. Backup time is not guaranteed here.",
    specs: spec([
      ["Rating", "600VA (sample)"],
      ["Use", "Short recorder backup"],
      ["Stock", "Out of stock in sample catalog"],
    ]),
  },
  {
    id: "kit-4",
    name: "4 camera home kit",
    brand: "Aurora Demo",
    model: "AD-K4",
    sku: "SAMPLE-AD-K4",
    categories: ["cctv-kits", "cctv-cameras"],
    seller: "rampuria-mart",
    image: { type: "collage", sources: ["/images/dome-cam.jpg", "/images/bullet-cam.jpg", "/images/nvr.jpg"], alt: "Collage of a dome camera, a bullet camera and a recorder" },
    alt: "Collage of a dome camera, a bullet camera and a recorder",
    mrp: 18999,
    price: 15999,
    stock: 3,
    warranty: "As per items · sample label",
    rating: 4.6,
    resolution: "Mixed 2MP sample",
    lens: "Fixed",
    night: "IR on cameras · sample",
    storage: "HDD not included",
    connectivity: "Kit · confirm type on quote",
    description: "Sample 4-camera kit. Included items are listed on the package page. Installation is optional and quoted.",
    specs: spec([
      ["Cameras", "4 (sample mix)"],
      ["Recorder", "Included in this sample kit"],
      ["HDD", "Not included"],
      ["Cable and power", "Starter lengths · sample"],
      ["Installation", "Optional, not included in product price"],
    ]),
  },
  {
    id: "mount-kit",
    name: "Mount and junction accessory set",
    brand: "Line Demo",
    model: "LD-MK",
    sku: "SAMPLE-LD-MK",
    categories: ["accessories"],
    seller: "karni-cctv",
    image: "/images/svg/accessories.svg",
    alt: "Illustration of small mounting accessories",
    mrp: 899,
    price: 649,
    stock: 14,
    warranty: "Parts · sample label",
    rating: 4.0,
    resolution: "—",
    lens: "—",
    night: "—",
    storage: "—",
    connectivity: "—",
    description: "Sample accessory set for mounts and a junction box. Exact hardware depends on the wall.",
    specs: spec([
      ["Contents", "Mount hardware · sample set"],
      ["Use", "Installation support"],
    ]),
  },
];

export const services = [
  {
    id: "cctv-installation",
    name: "CCTV Installation",
    short: "Mounting, cabling, recorder setup and a playback walkthrough.",
    priceType: "starting",
    startingPrice: 1499,
    duration: "About 2–6 hours for a small home. Larger sites are quoted.",
    warranty: "Workmanship terms come from the professional’s quote. No platform-wide warranty is live.",
    image: "/images/install-scene.jpg",
    alt: "Technician fitting a camera under a shop awning",
    included: ["Mounting for the agreed camera count", "Recorder placement", "Basic cable routing", "Power-on and recording test", "Date and time setup", "Short playback walkthrough"],
    excluded: ["Extra cameras beyond the booking", "Civil work or long trenching", "Router or internet plan", "Materials unless added on the quote"],
    description: "Book a sample installation request for a home or a small business. Final scope and price depend on camera count, cable runs and whether materials are included.",
  },
  {
    id: "cctv-repair",
    name: "CCTV Repair",
    short: "Camera, recorder, power, cable and viewing faults.",
    priceType: "quote",
    startingPrice: null,
    duration: "Diagnosis visit, then work if you accept a quote.",
    warranty: "Repair warranty, if any, is stated on the accepted quote.",
    image: "/images/nvr.jpg",
    alt: "A network recorder, often involved in repair visits",
    included: ["Fault check against the request you submit", "A quote before paid repair work", "Basic test after the agreed repair"],
    excluded: ["Replacement parts unless listed on the quote", "Damage outside the agreed fault", "New installation of extra cameras"],
    description: "Use this when an existing system is down. Price is not fixed. A professional would inspect notes and photos, then send a quote.",
  },
  {
    id: "cctv-maintenance",
    name: "CCTV Maintenance",
    short: "Cleaning, focus, recording check and a short health note.",
    priceType: "starting",
    startingPrice: 799,
    duration: "About 1–2 hours for a small system.",
    warranty: "Visit outcome is recorded on the job. No live warranty record in this preview.",
    image: "/images/dome-cam.jpg",
    alt: "Indoor dome camera",
    included: ["External cleaning of agreed cameras", "Recording and storage check", "Time setting check", "A short note of what was found"],
    excluded: ["Parts replacement", "Rewiring", "New cameras"],
    description: "A maintenance visit for a system that is already installed. It is not a repair quote and not an AMC plan.",
  },
  {
    id: "amc",
    name: "AMC",
    short: "Annual maintenance conversations for periodic checks.",
    priceType: "starting",
    startingPrice: 2499,
    duration: "Plan length is yearly in this sample. Visits are scheduled later.",
    warranty: "Coverage is whatever the signed AMC terms say. No plan is active here.",
    image: "/images/hero-camera.jpg",
    alt: "Camera on a home exterior",
    included: ["Sample plan outline: periodic inspection", "Recording and storage check", "A contact path for agreed faults"],
    excluded: ["Unlimited free parts", "New installations", "Coverage before a plan is actually issued"],
    description: "AMC is an annual maintenance contract. This page explains the idea. You cannot buy a live AMC in this preview.",
  },
  {
    id: "cctv-inspection",
    name: "CCTV Inspection",
    short: "A written look at an existing system before you spend more.",
    priceType: "starting",
    startingPrice: 499,
    duration: "About 45–90 minutes on a small site.",
    warranty: "Inspection is advisory. It is not a repair warranty.",
    image: "/images/bullet-cam.jpg",
    alt: "Outdoor bullet camera",
    included: ["Visual check of cameras and recorder", "Note of obvious faults", "Suggestion on what to quote next"],
    excluded: ["Repair work", "Parts", "A guarantee that every hidden fault will be found"],
    description: "Ask for an inspection when you want a clear picture before repair or replacement. The visit fee in this catalog is a sample starting figure.",
  },
  {
    id: "dvr-nvr-service",
    name: "DVR/NVR Service",
    short: "Recorder not booting, no display, or storage warnings.",
    priceType: "quote",
    startingPrice: null,
    duration: "Depends on the fault. Often a bench or on-site look.",
    warranty: "Stated only if a repair quote is accepted.",
    image: "/images/nvr.jpg",
    alt: "Black network video recorder",
    included: ["Recorder power and display check", "Storage warning look", "Quote if a disk or repair is needed"],
    excluded: ["A new recorder unless you buy one", "Camera replacement", "Internet provider faults"],
    description: "For DVR or NVR faults: no image, no recording, disk errors, or a recorder that does not start.",
  },
  {
    id: "cctv-wiring",
    name: "CCTV Wiring",
    short: "New runs, replacements and tidier cable routes.",
    priceType: "quote",
    startingPrice: null,
    duration: "Set after a look at distance and route.",
    warranty: "Cable workmanship, if offered, is on the quote.",
    image: "/images/install-scene.jpg",
    alt: "Installation work on a shopfront",
    included: ["Route discussion", "Quote for cable and labour", "Test of the agreed run"],
    excluded: ["Concealed civil work unless quoted", "Cameras and recorders unless added"],
    description: "Wiring is measured, not guessed. Send photos of the route if you have them. A quote follows.",
  },
  {
    id: "remote-viewing",
    name: "Remote Viewing",
    short: "Phone or remote playback setup on an existing system.",
    priceType: "starting",
    startingPrice: 699,
    duration: "About 30–90 minutes if the network is ready.",
    warranty: "Setup support window, if any, is on the booking note.",
    image: "/images/wifi-cam.jpg",
    alt: "Indoor camera that may be viewed remotely",
    included: ["App or client setup on one phone", "A test that live view opens", "A short note of the login path you should keep"],
    excluded: ["A new internet connection", "Router replacement", "Fixing an ISP outage"],
    description: "Remote viewing needs a working recorder or camera and a network. This service does not include a data plan.",
  },
  {
    id: "ip-camera-setup",
    name: "IP Camera Setup",
    short: "Addressing, NVR add, and a basic network check.",
    priceType: "starting",
    startingPrice: 899,
    duration: "About 1–3 hours for a few cameras.",
    warranty: "Configuration note only, unless a wider install is quoted.",
    image: "/images/poe-switch.jpg",
    alt: "PoE switch used with IP cameras",
    included: ["Add agreed cameras to the recorder", "Basic IP and password setup", "Live view test"],
    excluded: ["Full building network redesign", "Switch or cable if not already suitable"],
    description: "For IP cameras that are already mounted, or being added to an NVR. Larger network jobs can be quoted separately.",
  },
  {
    id: "wifi-camera-setup",
    name: "Wi-Fi Camera Setup",
    short: "Join a camera to the existing wireless network.",
    priceType: "starting",
    startingPrice: 599,
    duration: "About 30–60 minutes per simple camera.",
    warranty: "No coverage for later Wi-Fi dropouts caused by the router or walls.",
    image: "/images/wifi-cam.jpg",
    alt: "White Wi-Fi camera",
    included: ["Connect to the network you provide", "App setup on one phone", "A placement note if the signal is weak"],
    excluded: ["Mesh or router upgrade", "Cabling a dead zone"],
    description: "Wi-Fi setup uses your existing router. Thick walls and distance can still block a stable link.",
  },
  {
    id: "4g-camera-setup",
    name: "4G Camera Setup",
    short: "SIM camera placement, power and a first remote test.",
    priceType: "quote",
    startingPrice: null,
    duration: "Depends on mount height and signal.",
    warranty: "Signal and data charges are not guaranteed by the platform.",
    image: "/images/4g-cam.jpg",
    alt: "4G camera with solar panel",
    included: ["Mount discussion", "First configuration if the SIM and power are ready", "A test view"],
    excluded: ["SIM and data plan", "A promise of network coverage", "Pole fabrication unless quoted"],
    description: "4G cameras need signal, a SIM and power. Those are confirmed on a quote, not assumed.",
  },
];

export const repairIssues = [
  { id: "camera-dead", name: "Camera not working", service: "cctv-repair" },
  { id: "dvr", name: "DVR issue", service: "dvr-nvr-service" },
  { id: "nvr", name: "NVR issue", service: "dvr-nvr-service" },
  { id: "recording", name: "Recording issue", service: "dvr-nvr-service" },
  { id: "hdd", name: "HDD issue", service: "dvr-nvr-service" },
  { id: "power", name: "Power issue", service: "cctv-repair" },
  { id: "cable", name: "Cable issue", service: "cctv-wiring" },
  { id: "remote", name: "Remote viewing issue", service: "remote-viewing" },
  { id: "ip", name: "IP camera issue", service: "ip-camera-setup" },
  { id: "wifi", name: "Wi-Fi camera issue", service: "wifi-camera-setup" },
];

export const packages = [
  {
    id: "pkg-2",
    name: "2 Camera Package",
    cameras: 2,
    starting: 8499,
    image: "/images/dome-cam.jpg",
    alt: "White dome camera representing a small package",
    bestFor: "A small shop counter or a two-point home entry.",
    includes: ["2 cameras · sample mix", "DVR or NVR", "Starter cable", "Power supply", "Connectors", "Installation optional"],
    excludes: ["Hard disk unless added", "Extra cable beyond the starter length", "Network router"],
  },
  {
    id: "pkg-4",
    name: "4 Camera Package",
    cameras: 4,
    starting: 14999,
    image: "/images/bullet-cam.jpg",
    alt: "White bullet camera representing a four-camera package",
    bestFor: "A typical home or a single shopfront with a yard.",
    includes: ["4 cameras · sample mix", "DVR or NVR", "Starter cable", "Power supply", "Connectors", "Installation optional"],
    excludes: ["Hard disk unless added", "Long boundary runs", "4G SIM or internet plan"],
    featured: true,
  },
  {
    id: "pkg-6",
    name: "6 Camera Package",
    cameras: 6,
    starting: 21499,
    image: "/images/ptz-cam.jpg",
    alt: "PTZ camera representing a larger package",
    bestFor: "A larger home, office floor or warehouse corner.",
    includes: ["6 cameras · sample mix", "Recorder sized for the count", "Cable allowance · sample", "Power", "Connectors", "Installation optional"],
    excludes: ["PoE switch if the design needs one extra", "Civil work", "Monitor"],
  },
  {
    id: "pkg-8",
    name: "8 Camera Package",
    cameras: 8,
    starting: 27999,
    image: "/images/4g-cam.jpg",
    alt: "Outdoor camera representing an eight-camera package",
    bestFor: "A multi-room business or a site with several entries.",
    includes: ["8 cameras · sample mix", "8-channel recorder", "Cable allowance · sample", "Power", "Connectors", "Installation optional"],
    excludes: ["Extra HDD capacity", "Rack, monitor and UPS unless added", "Multi-floor civil work"],
  },
];

export const faqs = [
  { q: "How does CCTV installation work?", a: "You choose installation, share camera count, address and a preferred time, and optionally a photo. A nearby professional would review it and either accept a starting price or send a quote. Work is tracked from visit to completion. In this preview the request stays on your device." },
  { q: "How do I book a repair?", a: "Open CCTV Repair, describe the fault, and add photos if you can. Repair prices are quoted after a look at the problem. Booking here creates a local draft, not a dispatched technician." },
  { q: "Can I buy CCTV and installation together?", a: "Yes. Add a product and choose Get installation, or open a package and add the installation option. Installation remains a request or a starting estimate until a professional confirms the site." },
  { q: "How do I get a quote?", a: "Use Get quote on a service or a professional profile. You can accept, reject or ask for a change when a quote exists. A sample quote layout is available so you can see that screen. It was not sent by a professional." },
  { q: "How do I find a nearby professional?", a: "Set a city with the location control. Profiles are filtered to that city. Distance is not shown because live location matching is not connected. Every profile in this preview is sample data." },
  { q: "How do I track my order?", a: "My Orders holds drafts you save on this device. A separate sample timeline shows the service and product stages. That timeline is a layout preview, not your order." },
  { q: "What is AMC?", a: "AMC is an annual maintenance contract: periodic checks and an agreed support path. Plans are explained on the AMC page. None can be purchased as a live contract here." },
  { q: "Can I request a repair for my existing CCTV?", a: "Yes. You do not have to buy a new system. Book CCTV Repair or DVR/NVR Service and describe the equipment you already have." },
  { q: "How does payment work?", a: "The intended gateways are Razorpay and Cashfree, verified on the server. They are not connected in this preview. You will not be charged, and a paid order will not be created." },
];

export const serviceFaqs = {
  "cctv-installation": [
    { q: "Is the starting price the final bill?", a: "No. It is a sample labour starting point. Cable length, camera count and materials can change the quote." },
    { q: "Do I need to be at home?", a: "Someone who can show mounting points and the router or power location should be there." },
  ],
  "cctv-repair": [
    { q: "Why is there no fixed price?", a: "A dead camera, a failed disk and a cut cable are different jobs. The quote lists material and labour before you accept." },
  ],
  amc: [
    { q: "Is an AMC active if I browse this page?", a: "No. Nothing is billed and no visit is scheduled." },
  ],
};

export const sampleReviews = [
  { id: "r1", target: "dome-2mp", kind: "product", author: "Sample reviewer A", date: "12 Mar 2026", rating: 5, text: "Layout sample. This is not a verified purchase review." },
  { id: "r2", target: "bullet-4mp", kind: "product", author: "Sample reviewer B", date: "02 Feb 2026", rating: 4, text: "Layout sample about image clarity. Not a real customer." },
  { id: "r3", target: "karni-cctv", kind: "shop", author: "Sample reviewer C", date: "18 Jan 2026", rating: 5, text: "Layout sample about counter service. Not a real shop review." },
  { id: "r4", target: "r-sharma", kind: "professional", author: "Sample reviewer D", date: "09 Dec 2025", rating: 5, text: "Layout sample about a tidy install. Not a completed NAYAN SECURITY job." },
  { id: "r5", target: "cctv-installation", kind: "service", author: "Sample reviewer E", date: "21 Nov 2025", rating: 4, text: "Layout sample about booking clarity. Not a genuine service review." },
];

export const testimonials = [
  { quote: "I could see the camera count, the visit window and the quote on one screen.", who: "Sample homeowner · layout only", city: "Bikaner" },
  { quote: "The shop list and the installer list were separate, which is what I needed.", who: "Sample shopkeeper · layout only", city: "Jaipur" },
  { quote: "Tracking showed when work started and when I was asked to confirm.", who: "Sample office manager · layout only", city: "Jodhpur" },
];

export const gallery = [
  { src: "/images/install-scene.jpg", alt: "Technician installing a camera on a shopfront", caption: "Installation · sample photo, not a NAYAN SECURITY project" },
  { src: "/images/hero-camera.jpg", alt: "Camera mounted on a limestone home", caption: "Home exterior · sample photo, not a NAYAN SECURITY project" },
  { src: "/images/bullet-cam.jpg", alt: "Outdoor bullet camera", caption: "Camera replacement reference · sample product photo" },
  { src: "/images/nvr.jpg", alt: "Network recorder", caption: "DVR/NVR setup reference · sample product photo" },
];

export const trustPoints = [
  { title: "Verified professionals", text: "The badge is designed in. A profile is called verified only after it passes the platform check. That check is not live in this preview." },
  { title: "Local service", text: "Shops and professionals are listed by city and area so you are not calling across the state by default." },
  { title: "Transparent quotes", text: "Material, labour, travel and the total sit on one quote. You accept, reject or ask for a change." },
  { title: "Secure payments", text: "Razorpay or Cashfree, confirmed on the server. The gateway is not connected here, so nothing is charged." },
  { title: "Order tracking", text: "Service jobs and product deliveries have their own stages, from booking or confirmation through to close." },
  { title: "Product + installation", text: "Buy the kit and add installation on the same path, instead of coordinating two vendors yourself." },
  { title: "Warranty support", text: "Warranty period, dates and terms are stored with the item when a real order exists. None are active in this preview." },
  { title: "AMC support", text: "Annual checks can be added after installation. Plans are explained, not sold as live contracts yet." },
];

export const steps = [
  { n: "01", title: "Select service or product", text: "Start from a camera, a package, or a job such as install, repair or AMC." },
  { n: "02", title: "Connect with shop or professional", text: "See sample shops and professionals for the city you picked." },
  { n: "03", title: "Confirm order or quote", text: "Fixed catalog prices stay on the product. Site work can wait for a quote." },
  { n: "04", title: "Get service or delivery", text: "Track the visit or the parcel. Confirm completion when the work is actually done." },
];

export const legal = {
  terms: {
    title: "Terms",
    body: [
      "NAYAN SECURITY is a marketplace concept that connects customers with CCTV shops and professionals. The company does not personally perform every installation.",
      "This website is a preview. Catalog prices, profiles, reviews and package contents are sample content. They are not an offer you can accept as a binding contract today.",
      "When the platform is live, orders, quotes, cancellations and provider duties will follow published terms, seller agreements and professional agreements. Those documents are not final here.",
      "Do not treat a sample quote, sample rating or sample verified-style badge as a statement about a real person or shop.",
    ],
  },
  privacy: {
    title: "Privacy",
    body: [
      "A live NAYAN SECURITY platform would collect account details, addresses, order history and photos you upload so a job can be fulfilled. That data would be limited to people who need it for the order.",
      "In this preview, drafts, cart lines and addresses you type are stored in this browser only. They are not sent to a NAYAN SECURITY server. Photos you select are not uploaded.",
      "Payment card data is not collected here. A future gateway checkout would be handled by the payment provider, with verification on the server.",
      "Location permission is optional. You can type a city or PIN code instead. This preview does not require GPS.",
    ],
  },
  refund: {
    title: "Refund and cancellation",
    body: [
      "A live policy would state when a product order or a service booking can be cancelled, what fee applies, and when a refund is eligible.",
      "That policy is not published as a binding rule in this preview. Do not assume a refund amount.",
      "Because payments are not connected, this preview cannot start, process or complete a refund.",
      "If a future order is cancelled, the status, any charge and the refund state should be shown plainly. A refund is not complete until the payment provider confirms it.",
    ],
  },
  warranty: {
    title: "Warranty",
    body: [
      "Product warranty and installation workmanship are different. A camera may carry a seller or manufacturer term. A cable run may carry a shorter workmanship term from the professional.",
      "Warranty labels in the catalog are sample text. They are not a promise from NAYAN SECURITY or from a manufacturer.",
      "A live record would show the period, start date, end date, covered item and claim status. Your profile has no warranty records until a real purchase exists.",
    ],
  },
  amc: {
    title: "AMC",
    body: [
      "An annual maintenance contract can include periodic inspection, recording checks, and an agreed response for faults. Parts are not automatically free.",
      "Sample starting figures on the AMC service page are not a plan you have bought.",
      "Monthly, quarterly, half-yearly and yearly shapes may exist later. Coverage, visit count and price would be on the plan you accept.",
      "No AMC is active on this preview account.",
    ],
  },
};

export function cityName(id) {
  return cities.find((c) => c.id === id)?.name || id;
}

export function shopById(id) {
  return shops.find((s) => s.id === id);
}

export function productById(id) {
  return products.find((p) => p.id === id);
}

export function serviceById(id) {
  return services.find((s) => s.id === id);
}

export function proById(id) {
  return professionals.find((p) => p.id === id);
}

export function packageById(id) {
  return packages.find((p) => p.id === id);
}

export function categoryById(id) {
  return productCategories.find((c) => c.id === id);
}

export function discountPercent(p) {
  if (!p.mrp || p.mrp <= p.price) return 0;
  return Math.round((1 - p.price / p.mrp) * 100);
}

export function stockLabel(p) {
  if (p.stock <= 0) return { key: "out", text: "Out of stock · sample catalog" };
  if (p.stock <= 3) return { key: "low", text: `Low stock · ${p.stock} in sample catalog` };
  return { key: "ok", text: "In stock · sample catalog" };
}

export function reviewsFor(kind, id) {
  return sampleReviews.filter((r) => r.kind === kind && r.target === id);
}

export function searchAll(q) {
  const s = q.trim().toLowerCase();
  if (!s) return { products: [], services: [], professionals: [], shops: [] };
  const hit = (...parts) => parts.filter(Boolean).join(" ").toLowerCase().includes(s);
  return {
    products: products.filter((p) => hit(p.name, p.brand, p.model, p.description, p.categories.join(" "))),
    services: services.filter((sv) => hit(sv.name, sv.short, sv.description)),
    professionals: professionals.filter((p) => hit(p.name, p.business, p.area, p.bio)),
    shops: shops.filter((sh) => hit(sh.name, sh.area, sh.about, sh.productsNote)),
  };
}
